#if !canImport(ObjectiveC)
import XCTest

extension DefaultVerticalPlotModelTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DefaultVerticalPlotModelTests = [
        ("testBuilder", testBuilder),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DefaultVerticalPlotModelTests.__allTests__DefaultVerticalPlotModelTests),
    ]
}
#endif
